### ISSUE TITLE
Question about paper.

### ISSUE THREAD

**Issue by lc82111** [nv-tlabs/GSCNN#1]
Thanks for your share. 

Several questions:  

1. Does Eq.(6) miss a minus sign?
2. How to obtain the gradient of an image for the input of the shape stream? soble?
3. The regular steam outputs multi-scale feat-maps. How to obtain the attention maps at a resolution of HxW always?

**Comment by tovacinni** [comment]
Thanks for your interest in our work!

1. Yes, I believe Eq.(6) is missing a minus sign. We will fix this, thanks for point it out!

2. We use canny edges.

3. We use bilinear upsampling.

2/3. We plan on releasing the code soon, so hopefully these questions would be answered more accurately once that happens.

**Comment by arc144** [comment]
Thanks for your paper and reply. May I also ask a question?

1. How do you use the ASPP module to fuse the regular stream with shape stream? Do you apply ASPP only to regular stream, upsample it and then concatenate with shape stream followed by 1x1 conv?

1. In the shape stream figure there is a conv1x1 leading to another conv1x1 (from gradients) does it mean that you concat the results of both convolutions?

1. Finally, if I'm working in a binary context (foreground/background) may I simply replace the CE-losses for BCE and replace the argmax/gumbel softmax with a simple treshold?

Thanks a lot. Will the code be released this month?

**Comment by Nutakki2259** [comment]
Hi, When can i get the code for this project?

**Comment by tovacinni** [comment]
Thanks for your interest in our work!

@arc144 

1/2. We have released the code now so I think the code would better answer that question.

3. I believe so! We have tried our network with some private datasets in a binary context and results do seem to improve. Thresholding is one strategy, but you could also consider having 2 classes (foreground / background). 

@Nutakki2259 

The code has been released.
