### ISSUE TITLE
How to evaluate the edge score?

### ISSUE THREAD

**Issue by lxtGH** [nv-tlabs/GSCNN#20]
Hi! Thanks for your code. Could you tell me how to evaluate the edge which is reported in your paper. I want to evaluate it locally. Also how to generate the edges results in your demo. It looks so cool.

**Comment by tovacinni** [comment]
Thanks for the interest in our work, and sorry for the late reply!

Much of our edge evaluation code is contained within https://github.com/nv-tlabs/GSCNN/blob/master/train.py and https://github.com/nv-tlabs/GSCNN/blob/master/datasets/edge_utils.py . Feel free to let me know if you need more specific guidance on how to get this to work.
