### ISSUE TITLE
How to change number of gpus

### ISSUE THREAD

**Issue by shubhaminnani** [nv-tlabs/GSCNN#25]
Hi, i want to know how to use multiple gpu for training with multiple batch size .. and validate with single batch size @tovacinni @varunjampani @davidjesusacu @ShreyasSkandanS

**Comment by tovacinni** [comment]
Not sure what you mean exactly, but take a look at the parameters bs_mult and bs_mult_val.

**Comment by shubhaminnani** [comment]
thanks, will check this out
