### ISSUE TITLE
Training from scratch error 

### ISSUE THREAD

**Issue by kaushikb258** [nv-tlabs/GSCNN#28]
I tried training on cityscapes from scratch using 'python train.py' and get this error: 

raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

It is something in the _AtrousSpatialPyramidPoolingModule class in network/gscnn.py

img_features = self.img_conv(img_features)

**Comment by kaushikb258** [comment]
Actually got training to work with the following fix in ASPP (replaced AdaptiveAvgPool with AvgPool):

self.img_pooling = nn.AvgPool2d(1)  # nn.AdaptiveAvgPool2d(1)

But not sure why training is not working with AdaptiveAvgPool2d

**Comment by ly-mentaltity** [comment]
your batchsize is not even
