### ISSUE TITLE
Better IU than in paper

### ISSUE THREAD

**Issue by biboffff** [nv-tlabs/GSCNN#29]
Hi,

when executing 

`python train.py --evaluate --snapshot checkpoints/best_cityscapes_checkpoint.pth`

I achieve a slightly better IoU value than in your arxiv paper. Is the arxiv paper not up-to-date or is this a bug?

**Comment by tovacinni** [comment]
Yep, our released model is slightly better than what we initially report in the paper. This not a bug.
