### ISSUE TITLE
ImportError: CANN'T import name 'imsave'

### ISSUE THREAD

**Issue by Boyjingweizhang** [nv-tlabs/GSCNN#30]
While trying the train.py file, I have encountered the  Error "ImportError: CANN'T import name 'imsave'". This issue is caused by the version of scipy. In the scipy (version>1.3),the method "imsave" has been eliminated, so install the module scipy with lower version (1.2.0) can fix this error.

**Comment by luxiansheng96** [comment]
conda install scipy=1.2.1

**Comment by paul-adlink** [comment]
Yes, install scipy==1.2.0 can resolve this problem.
