### ISSUE TITLE
TypeError: __init__() takes 11 positional arguments but 12 were given

### ISSUE THREAD

**Issue by VaingloryD** [nv-tlabs/GSCNN#33]
While trying the train.py file, I have encountered the Error "TypeError: __init__() takes 11 positional arguments but 12 were given". Here is the wrong code:
class GatedSpatialConv2d(_ConvNd):
  ``
        super(GatedSpatialConv2d, self).__init__(
             in_channels, out_channels, kernel_size, stride, padding, dilation,
             False, _pair(0), groups, bias, 'zeros')
``

**Comment by yuki-0321** [comment]
You can try to install pytorch = 1.1.0. This may be a issue of pytorch's version.

**Comment by tovacinni** [comment]
Thanks for your interest in our work!

This is a duplicate issue, please refer to https://github.com/nv-tlabs/GSCNN/issues/6#issuecomment-525578150
