### ISSUE TITLE
Hi,i have a problem with the train data. There is a FileNotFoundError, no such file or directory /home/xie***/data/citysapes/leftImg8bit_trainvaltest/leftImg8bit/train

### ISSUE THREAD

**Issue by XieZixiUSTC** [nv-tlabs/GSCNN#37]

**Comment by paul-adlink** [comment]
I also met this problem. Seems we need to download the data set Cityscapes ourselves. Cause this is licensed and need to register so that could be downloaded. Hope this information is helpful for your progress.

**Comment by tovacinni** [comment]
The dataset needs to be downloaded on your own. Sorry!
