### ISSUE TITLE
Unused feature in forward pass?

### ISSUE THREAD

**Issue by benDavidson6** [nv-tlabs/GSCNN#39]
I'm just reading the paper and looking at the code to follow along. In doing so I've gotten a bit confused because there seems to be an extra shape feature map in the code. In `networks/gscnn.py` on line 274 we have
``` python
s1 = F.interpolate(self.dsn1(m1), x_size[2:], mode='bilinear', align_corners=True)
```
but this is never output or used. Following the paper I would expect this to be the input to the `self.res1` unit. However, this is not the case. What is actually put through that is
```python
m1f = F.interpolate(m1, x_size[2:], mode='bilinear', align_corners=True)
cs = self.res1(m1f)
```
Something is off here as we calculate `s1` but do nothing with it. My question is, should `s1` replace `m1f` or should it just be deleted?

**Comment by tovacinni** [comment]
Thanks for your interest in our work!

You are right, s1 is not needed- that's likely a variable we forgot to delete. m1 comes from the first layer in the resnet, so it follows the paper- s1 is essentially a duplicate variable. Will close this issue when I delete this. 

Let me double check, but I believe you are right. 

Following the paper,

**Comment by tovacinni** [comment]
https://github.com/nv-tlabs/GSCNN/commit/3648b86d822f3e73ab1d8e827cf47466bf8f01a7

**Comment by rajexp** [comment]
@tovacinni When I look at the paper there the Figure 2. All shape stream inputs from regular stream seem to be passing through conv1x1. 
![image](https://user-images.githubusercontent.com/33890781/100973377-74582b80-3560-11eb-95ea-732c0c539a6b.png)
Going by that `s1` should have been used in the first residual block `res1` contrary to what is presented in the code where `m1` being direct feature (conv3x3) of the regular stream is used.

Could you please look into this. Any possible explanation is appreciated.
