### ISSUE TITLE
few questions with interesting result, outstanding architecture of yours

### ISSUE THREAD

**Issue by wooramkang** [nv-tlabs/GSCNN#4]
1. interesting result, outstanding architecture! when can i read your codes

2. did your team consider more loss technics, something like VGG loss or something?

3. this architecture could be called as one of transformation of encoder-decoder, right?

not question but additionally, there is typo on regular stream part of page 3 in in paper.
fully-convoutional => fully-convolutional

thank you for reading it

**Comment by tovacinni** [comment]
Thanks for your interest in our work!

1. We have released the code!

2. We have considered several different loss functions, but have not tried VGG loss specifically. 

3. I think so!

Thanks for pointing out the typo, we will make amendments accordingly. :)

**Comment by akshaykvnit** [comment]
How is it a transformation of encoder-decoder? I think it is based on the fully convolutional with upsampling approach. The encoder-decoder architectures use transposed convolutions (deconvolutions) for upsampling, whereas this work uses bilinear interpolations for all upsampling.
