### ISSUE TITLE
How to load wide resnet pretrained model from IMGNET

### ISSUE THREAD

**Issue by GitHubLiaoYong** [nv-tlabs/GSCNN#41]
Thank for your great work and share your code,but i have same question,i can't finde the code  load wide resnet pretraned model from ImageNet.Can anyone help?thank you.

**Comment by GitHubLiaoYong** [comment]
I think we should write this code by ourself

**Comment by tovacinni** [comment]
Thanks for your interest in our work!

You can import any pretrained weights using the args we supply, but we don't necessarily officially support the code to automatically use weights where possible for diff output dimension sizes.
