### ISSUE TITLE
PyTorch (<= 1.0.0 ) ?

### ISSUE THREAD

**Issue by Tetsujinfr** [nv-tlabs/GSCNN#5]
In the install instructions you mention PyTorch (<= 1.0.0 ). I have pytorch 1.1, so does it means it is going to fail for sure or that you did not test with version above 1.0?
If the former, is there a reason why such a recent paper/code does not run on pytorch version beyond 1.0?
Thanks.

**Comment by Tetsujinfr** [comment]
ok, so I tried running the code with pytorch v1.1 and it failed.
Now, I have setup a new virtual env for your project only, where I did install pytorch 1.0.0. I am going through t)the dependencies installation currently (there are many dependencies you did not list in your readme but I can figure out hopefully.
So I am reaching the torchvision dependency (ModuleNotFoundError: No module named 'torchvision'), then I am like doing pip3 install torchvision but then it tries to install pytoch1.2.
So I kill it and I am trying to prevent this, but on the pypi webpage of torchvision (https://pypi.org/project/torchvision/) they say "TorchVision requires PyTorch 1.1 or newer."

So your project requires pytorch <=1.0.0 but your project has a dependency on torchvision which itself requires pytorch v1.1 or above... please help me resolve this indefinite loop!!!
thanks a lot

**Comment by tovacinni** [comment]
Thanks for your interest in our work! As mentioned in #6, the PyTorch versioning was a typo and I have now amended it. Using the newest versions for most things should in theory work, although you may need to make certain tweaks if there are deprecated functions etc. I can try to find out which exact versions I used for the dependencies.

**Comment by Tetsujinfr** [comment]
Thanks a lot for your help and clarifications. Great project. Closing this.
