### ISSUE TITLE
Evaluation code bug

### ISSUE THREAD

**Issue by ShreyasSkandanS** [nv-tlabs/GSCNN#7]
In train.py,

on line 139

```
if args.evaluate:
        # Early evaluation for benchmarking
        validate(val_loader, net, criterion_val,
                 optim, epoch, writer)
        evaluate(val_loader, net)
        return
```

The variable **'epoch'** is used before being defined. I was able to work my way around this by just passing 0 or 1 in place of epoch, since for pure evaluation purposes this is irrelevant.

```
if args.evaluate:
        # Early evaluation for benchmarking
        validate(val_loader, net, criterion_val,
                 optim, 1, writer)
        evaluate(val_loader, net)
        return
```

Maybe this is worth looking into. 

Best regards,
Shreyas

**Comment by Tetsujinfr** [comment]
I was about to log the same issue, you saved my day with this temp workaround. tx a lot.

**Comment by tovacinni** [comment]
Yes, this is a bug. Fixed as per https://github.com/nv-tlabs/GSCNN/pull/9 

Thanks @ShreyasSkandanS for the pull request!
