### ISSUE TITLE
result is not very good

### ISSUE THREAD

**Issue by jinfagang** [nv-tlabs/GSCNN#82]
Here is my test on single image with half size:

![image](https://user-images.githubusercontent.com/21303438/110442423-cc6d7380-80f5-11eb-9f17-ce79c04a75c7.png)

To be honest, the result is not very good.

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/110443025-71884c00-80f6-11eb-902d-bd7e42f038e5.png)

sorry, it's normal now.

**Comment by as24-asingla** [comment]
Can you give a sample code for single image prediction using saved model weights?
